Blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('MyBlogs.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('timeline', TemplateView.as_view(template_name='timeline.html'), name="timeline"),
    path('accounts/', include(('myaccount.urls', 'myaccount'), namespace='myaccount')),  # oauth,只展现一个用户登录界面
    path('comment/', include(('comment.urls', 'comment'), namespace='comment'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyBlogs/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:pk>/', views.article, name='article',),
    path('archive/<int:year>/<int:month>/', views.archive, name='archive'),
    path('category/<str:category>/', views.r_category, name='r_category'),
    path('search/', include('haystack.urls'), name='search'),
]

comment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # 发表评论，处理一级回复
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 处理多级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')

]

MyBlogs/models.py
from django.db import models
from django.urls import reverse
from mdeditor.fields import MDTextField


# Create your models here.

# 文章标签
class Tag(models.Model):
    tag_name = models.CharField(max_length=30, unique=True, verbose_name='标签')

    def __str__(self):
        return u'%s' % self.tag_name

    class Meta:
        ordering = ['id']
        verbose_name_plural = u'标签'


# 文章类别
class Category(models.Model):
    cname = models.CharField(max_length=30, unique=True, verbose_name='类别')

    def __str__(self):
        return u'%s' % self.cname

    class Meta:
        ordering = ['id']
        verbose_name_plural = u'类别'


# 文章信息
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name="标题", unique=True)
    author = models.CharField(max_length=20, verbose_name="博客作者")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="博客类别")
    summary = models.TextField(max_length=100, verbose_name="博客摘要")
    context = MDTextField(null=True, blank=True, verbose_name="博客内容")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_date = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    watch_number = models.PositiveIntegerField(default=0, verbose_name="观看数")
    tag = models.ManyToManyField(Tag, verbose_name="博客标签")
    is_valid = models.BooleanField(default=True)

    class Meta:
        ordering = ['-create_date']
        verbose_name_plural = u'文章'

    def __str__(self):
        return u'Article:%s' % self.title

    def sum_profile(self):
        if len(self.summary) > 10:
            return "{}......".format(self.summary[:10])
        else:
            return self.summary

    def con_profile(self):
        if len(self.context) > 10:
            return "{}......".format(self.context[:10])
        else:
            return self.context

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article', args=[self.id])

MyBlogs/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page

from .models import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from comment.models import Comment
from comment.forms import CommentForm


# 返回首页，传回分页数据
def index(request):
    page_number = request.GET.get('page', 1)
    blogs = Article.objects.all().order_by('-create_date')
    page_obj, page_list, page = pag(blogs, page_number)
    return render(request, 'MyBlogs/index.html', {'page_obj': page_obj, 'page_list': page_list, 'page': page})


# 博客文章
@cache_page(10)
def article(request, pk):
    blog = Article.objects.get(pk=pk)
    # 获取评论
    comments = Comment.objects.filter(article=pk)
    # 引入评论表单
    comment_form = CommentForm()
    # 获取评论数目
    c_number = Comment.objects.filter(article_id=pk)
    # 浏览量 +1
    blog.watch_number += 1
    blog.save(update_fields=['watch_number'])
    context = {'blog': blog, 'comments': comments, 'c_number': c_number, 'comment_form': comment_form, }
    return render(request, 'MyBlogs/blog.html', context)


# 实现分类跳转
def r_category(request, category):
    page_number = request.GET.get('page', 1)
    ca_article = Article.objects.filter(category__cname=category)
    page_obj, page_list, page = pag(ca_article, page_number)
    return render(request, 'MyBlogs/index.html', {'page_obj': page_obj, 'page_list': page_list, 'page': page})


# 根据日期返回博客，实现归档跳转
def archive(request, year, month):
    page_number = request.GET.get('page', 1)
    ar_article = Article.objects.filter(create_date__year=year, create_date__month=month)
    page_obj, page_list, page = pag(ar_article, page_number)
    return render(request, 'MyBlogs/index.html', {'page_obj': page_obj, 'page_list': page_list, 'page': page})


# 分页功能,传回分页数据，
# page_obj为当前请求页面，
# page为总分页数据，
# page_list为当前页面附近几个页面分页值
def pag(pages, page_number):
    page = Paginator(pages, 2)
    try:
        page_obj = page.get_page(page_number)
    except PageNotAnInteger:
        page_obj = page.get_page(1)
    except EmptyPage:
        page_obj = page.get_page(page.num_pages)

    begin = int(page_number) - 2
    if begin < 1:
        begin = 1
    end = begin + 4
    if end > page.num_pages:
        end = page.num_pages
    if end < 5:
        begin = 1
    else:
        begin = end - 4
    page_list = range(begin, end + 1)

    return page_obj, page_list, page

templates/MyBlogs/blog.html
{% extends 'base.html' %}
{% load mptt_tags %}
{% load my_filters %}
{% load static %}
{% block style %}
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}"/>
{% endblock %}

{% block title %}
    <title>{{ blog.title }}</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class=" col-lg-9 col-xl-10">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white"  >
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'r_category' blog.category %}">{{ blog.category }}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ blog.title }}</li>
                    </ol>
                </nav>
                <div class="card rounded-0 border-0" id="article">
                    <div class="card-body px-2 px-md-3 pb-0">
                        <h1 class="card-title text-center font-weight-bold text-info">{{ blog.title }}</h1>
                        <hr>
                        <div class="text-center f-13">
                            <span class="mx-2" data-toggle="tooltip" data-placement="bottom" title="最后编辑于{{ blog.update_date }}" >{{ blog.update_date | date:"Y-m-d" }}</span>
                            <span class="mx-2" title="观看数">观看数 {{ blog.watch_number }}</span>
                            <span class="mx-2" title="评论">评论 0</span>
                        </div>
                        <div class="article-body mt-4 f-17" id="article_content" style="-webkit-box-sizing: border-box;-moz-box-sizing: border-box;">
                            <p style="display: none">
                                {{ blog.context|mard|safe }}
                            </p>
                        </div>

                        <!-- 发表评论 -->
                        <hr>
                        {% if user.is_authenticated %}
                            <div>
                                <form
                                    action="{% url 'comment:post_comment' blog.id %}"
                                    method="POST"
                                >
                                {% csrf_token %}
                                    <div class="form-group">
                                        <label for="body">
                                            <strong>
                                                我也要发言：
                                            </strong>
                                        </label>
                                        <div>
                                            {{ comment_form.media }}
                                            {{ comment_form.body }}
                                        </div>
                                    </div>
                                    <!-- 提交按钮 -->
                                    <button type="submit" class="btn btn-primary ">发送</button>
                                </form>
                            </div>
                            <br>
                        {% else %}
                            <br>
                            <h5 class="row justify-content-center">
                                请<a href="{% url 'account_login' %}">登录</a>后回复
                            </h5>
                            <br>
                        {% endif %}

                        <!-- 显示评论 -->
                        <h4>共有{{ comments.count }}条评论</h4>
                        <div class="row">
                            <!-- 遍历树形结构 -->
                            {% recursetree comments %}
                                <!-- 给 node 取个别名 comment -->
                                {% with comment=node %}
                                    <div class="{% if comment.reply_to %}
                                                 offset-1 col-11
                                                 {% else %}
                                                 col-12
                                                {% endif %}"
                                    >
                                        <hr>
                                        <p>
                                            {% if comment.reply_to %}
                                                <i class="far fa-arrow-alt-circle-right"
                                                   style="color: cornflowerblue"
                                                ></i>
                                                <strong style="color: pink">
                                                    {{ comment.reply_to }}
                                                    回复
                                                </strong>

                                            {% endif %}

                                            <strong style="color: pink">
                                                    {{ comment.user }}
                                            </strong>
                                        </p>
                                        <div>{{ comment.body|safe }}</div>

                                        <div>
                                            <span style="color: gray">
                                                {{ comment.created|date:"Y-m-d H:i" }}
                                            </span>

                                            <!-- 加载 modal 的按钮 -->
                                            {% if user.is_authenticated %}
                                                <button type="button"
                                                        class="btn btn-light btn-sm text-muted"
                                                        onclick="load_modal({{ blog.id }}, {{ comment.id }})"
                                                >
                                                    回复
                                                </button>
                                            {% else %}
                                                <a class="btn btn-light btn-sm text-muted"
                                                    href="{% url 'account_login' %}"
                                                >
                                                    回复
                                                </a>
                                            {% endif %}
                                        </div>

                                        <!-- Modal -->
                                        <div class="modal fade"
                                             id="comment_{{ comment.id }}"
                                             tabindex="-1"
                                             role="dialog"
                                             aria-labelledby="CommentModalCenter"
                                             aria-hidden="true"
                                        >
                                            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                                <div class="modal-content" style="height: 480px">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                                    </div>
                                                    <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                                </div>
                                            </div>
                                        </div>
                                        {% if not comment.is_leaf_node %}
                                            <div class="children">
                                                {{ children }}
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endwith %}
                            {% endrecursetree %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--前后文章-->
{% endblock %}
{% block scripts %}
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>

    <script>
        // 加载 modal
        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' +
                    article_id +
                    '/' +
                    comment_id +
                    '"' +
                    ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                    comment_id +
                    '"></iframe>';
                $(modal_body).append(content);
            };

            $(modal_id).modal('show');
        }
    </script>
{% endblock %}

templates/MyBlogs/index.html
{% extends 'base.html' %}
{% load static %}
{% load my_filters %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/index.css">
{% endblock %}
{% block title %}
    <title>MyBlogs</title>
{% endblock %}
{% block content %}
    {# 博客模块开始 #}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                {# 文章内容显示 #}
                <div class="summary-list">
                {% for blog in page_obj %}
                    <div class="card mb-1 mb-sm-2 p-2 p-lg-3 mt-4 ">
                        <div class="card-body">
                            <h2 class="header1 font-weight-bold">
                                <a class="header-a" style="color: #28a745" href="/article/{{ blog.id }}/">{{ blog.title }}</a>
                            </h2>
                            <div class="text-muted mb-2 f-12" style="font-size: smaller">
                                <span title="创建日期">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar-minus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path fill-rule="evenodd" d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                                      <path fill-rule="evenodd" d="M5.5 9.5A.5.5 0 0 1 6 9h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z"/>
                                    </svg>
                                    {{ blog.create_date | date:"y-m-d" }}
                                </span>
                            </div>
                            <p class="card-text d-sm-block mb-2 f-15">
                                {{ blog.summary }}
                            </p>
                            <div class="text-muted mb-0 f-12" style="font-size: smaller">
                                <a class="cate" href="{% url 'r_category' blog.category %}" title="分类" style="color: #4e555b">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-journal-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                                      <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                                      <path fill-rule="evenodd" d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                    </svg>
                                    <i class="fa fa-book mr-1"></i>{{ blog.category }}
                                </a>
                                <a class="as ml-3 mr-1" title="阅读数" style="color: #4e555b">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
                                      <path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                    </svg>
                                    {{ blog.watch_number }}
                                </a>
                                <a class="ac ml-3 mr-3"  href="#" target="_blank" title="评论" style="color: #4e555b">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-square-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h2.5a2 2 0 0 1 1.6.8L8 14.333 9.9 11.8a2 2 0 0 1 1.6-.8H14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                      <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                                    </svg>
                                    {{ blog.id | get_comment_number }}
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                {# 文章内容结束 #}

                {# 分页开始 #}
                <div class="text-center mt-2 mt-sm-1 mt-md-0 mb-3 f-16">
                    <nav aria-label="page navigation">
                        <ul class="pagination justify-content-center" >
                            <li class="page-item ">
                                <a class="page-link" href="?page=1">
                                    首页
                                </a>
                            </li>

                            {% if page_obj.has_previous %}
                                <li class="page-item ">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="上一页">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                </li>
                            {% endif %}

                            {% for page in page_list %}
                            <li class="page-item "><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li class="page-item ">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="下一页">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}

                            <li class="page-item ">
                                <a class="page-link" href="?page={{ page.num_pages }}">
                                   末页
                                </a>
                            </li>
                        </ul>

                    </nav>
                </div>
                {# 分页结束#}
            </div>
            <div class="col-lg-4">
                {% include 'base_right.html' %}
            </div>
        </div>
    </div>
    {# 博客模块结束 #}
{% endblock %}

templates/MyBlogs/login.html
{% extends 'base.html' %}
{% block title %}
    <title>登陆</title>
{% endblock %}

{% block content %}
<!-- 登陆表单开始 -->
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5" style="padding-top: 50px">
            <div class="card px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2">
                    <h3 class="my-1 text-info">登陆</h3>
                </div>
                <div class="card-body card-login">
                    <form class="login" method="post" action="{% url 'login' %}" name="login">
                        {%csrf_token%}
                        <div class="div_id_login">
                            <label for="login_email"></label>
                            <div>
                                <input type="email" id="login_email" class="form-control" placeholder="邮箱或用户名" name="login_email" value="{{ email }}" required autofocus>
                            </div>
                        </div>
                        <div class="div_id_password">
                            <label for="login_password"></label>
                            <div>
                                <input type="password" id="login_password" class="form-control" placeholder="密码" name="login_password" value="{{ pwd }}" required>
                            </div>
                        </div>
                        <div class="checkbox mb-1">
                            <center>
                            <div class="div_id_remember mt-2">
                                <input type="checkbox" id="remember" name="remember" value="remember-me">
                                <label for="remember">记住我</label>
                            </div>
                            </center>
                        </div>
                        <div class="mt-1">
                            <center><button class="btn btn-primary" type="submit">登陆</button></center>
                        </div>

                    </form>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title">
                        <span>快速登录</span>
                    </div>
                    <div class="login-link">
                        <a class="mx-4" href="#" title="社交账号登录有点慢，请耐心等候！"><i class="fa fa-weibo fa-2x"></i></a>
                        <a class="mx-4" href="#" title="社交账号登录有点慢，请耐心等候！"><i class="fa fa-github fa-2x"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- 登陆表单结束 -->
{% endblock %}

templates/MyBlogs/register.html
{% extends 'base.html' %}

{# 标题 #}
{% block title %}
    <title>注册</title>
{% endblock %}


{# 注册表单 #}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card px-3 px-lg-4 mt-4" >
                <div class="card-header text-center bg-white py-2">
                    <h3 class="my-1 text-info">注册</h3>
                </div>
                <div class="card-body card-login">
                    <form class="form-horizontal" method="post" action="{% url 'register' %}" name="register">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="register_email"></label>
                            <input type="email" class="form-control" placeholder="邮箱" name="register_email" id="register_email" required>
                        </div>
                        <div class="form-group">
                            <label for="register_name"></label>
                            <input type="text" class="form-control" placeholder="用户名" name="register_name" id="register_name" required>
                        </div>
                        <div class="form-group">
                            <label for="register_pwd1"></label>
                            <input type="password" class="form-control" placeholder="密码" name="register_pwd1" id="register_pwd1" required>
                        </div>
                        <div class="form-group">
                            <label for="register_pwd2"></label>
                            <input type="password" class="form-control" placeholder="确认密码" name="register_pwd2" id="register_pwd2" required>
                        </div>
                        <div class="form-group form-check ">
                            <center>
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </center>
                        </div>
                        <div>
                            <center><button type="submit" class="btn btn-primary">Submit</button></center>
                        </div>
                    </form>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title">
                        <span>快速登录</span>
                    </div>
                    <div class="login-link">
                        <a class="mx-4" href="#" title="社交账号登录有点慢，请耐心等候！"><i class="fa fa-weibo fa-2x"></i></a>
                        <a class="mx-4" href="#" title="社交账号登录有点慢，请耐心等候！"><i class="fa fa-github fa-2x"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}